
CREATE DATABASE project;
use project;

CREATE TABLE users (
    id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username varchar(255) UNIQUE,
    password varchar(255)
);

-- Create the products table
CREATE TABLE books (
    id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    userid int NOT NULL,
    title varchar(255) NOT NULL,
    author varchar(255) NOT NULL,
    year int NOT NULL,
    synopsis varchar(255) NOT NULL,
    editorial varchar(255) NOT NULL,
    description varchar(255),
    FOREIGN KEY (userid) REFERENCES users(id)
);

-- Insert example products
INSERT INTO users VALUES (null, "juan", "123"),
    (null, "daniel", "456"),
    (null, "jhuly", "789");

INSERT INTO books VALUES 
(null, 1, 'El viaje del héroe', 'José Manuel', 2015, 'Un joven emprende una aventura épica', 'Editorial Aventura', 'Una historia cautivadora'),
(null, 1, 'Cien años de soledad', 'Gabriel García Márquez', 1967, 'La historia de la familia Buendía', 'Editorial Sudamericana', 'Un clásico de la literatura'),
(null, 1, 'El principito', 'Antoine de Saint-Exupéry', 1943, 'Un niño que viaja entre planetas', 'Editorial Salamandra', 'Una fábula sobre la vida'),
(null, 1, '1984', 'George Orwell', 1949, 'Una distopía sobre el totalitarismo', 'Editorial Debate', 'Un libro impactante'),
(null, 1, 'El Alquimista', 'Paulo Coelho', 1988, 'Un viaje hacia la realización personal', 'Editorial Planeta', 'Inspirador'),
(null, 1, 'Harry Potter y la piedra filosofal', 'J.K. Rowling', 1997, 'Un niño en el mundo de la magia', 'Editorial Salamandra', 'Encantador'),
(null, 2, 'La sombra del viento', 'Carlos Ruiz Zafón', 2001, 'Un misterio en la Barcelona de la postguerra', 'Editorial Planeta', 'Absorbente'),
(null, 2, 'El túnel', 'Ernesto Sabato', 1948, 'La historia de un amor obsesivo', 'Editorial Seix Barral', 'Profundo'),
(null, 2, 'Orgullo y prejuicio', 'Jane Austen', 1813, 'Una crítica social sobre el matrimonio', 'Editorial Alianza', 'Un clásico romántico'),
(null, 2, 'Crónica de una muerte anunciada', 'Gabriel García Márquez', 1981, 'Un asesinato que todos conocen', 'Editorial Random House', 'Intrigante'),
(null, 2, 'El amor en los tiempos del cólera', 'Gabriel García Márquez', 1985, 'Una historia de amor duradera', 'Editorial Random House', 'Hermosa'),
(null, 2, 'Los ojos del perro siberiano', 'Antonio Garrido', 1998, 'Una historia sobre la lealtad', 'Editorial Planeta', 'Emotiva'),
(null, 3, 'El Hobbit', 'J.R.R. Tolkien', 1937, 'La aventura de un hobbit', 'Editorial Minotauro', 'Fascinante'),
(null, 3, 'Moby Dick', 'Herman Melville', 1851, 'La caza de una ballena blanca', 'Editorial Alianza', 'Un desafío literario'),
(null, 3, 'La guerra de los mundos', 'H.G. Wells', 1898, 'Una invasión marciana', 'Editorial Crítica', 'Impactante'),
(null, 3, 'Fahrenheit 451', 'Ray Bradbury', 1953, 'Un futuro donde los libros están prohibidos', 'Editorial Minotauro', 'Provocador'),
(null, 3, 'La casa de los espíritus', 'Isabel Allende', 1982, 'La historia de una familia a través de generaciones', 'Editorial Plaza & Janés', 'Mágico'),
(null, 3, 'El guardián entre el centeno', 'J.D. Salinger', 1951, 'Un adolescente rebelde en Nueva York', 'Editorial Alfaguara', 'Reflexivo'),
(null, 3, 'La metamorfosis', 'Franz Kafka', 1915, 'Un hombre se convierte en un insecto', 'Editorial Alianza', 'Extraño y fascinante'),
(null, 1, 'El juego del ángel', 'Carlos Ruiz Zafón', 2008, 'Un misterio literario en la Barcelona de los años 1920', 'Editorial Planeta', 'Intrigante'),
(null, 1, 'El arte de la guerra', 'Sun Tzu', -500, 'Estrategias de guerra y liderazgo', 'Editorial Debate', 'Un clásico atemporal'),
(null, 1, 'El código Da Vinci', 'Dan Brown', 2003, 'Un thriller lleno de enigmas', 'Editorial Planeta', 'Emocionante'),
(null, 1, 'Sapiens: De animales a dioses', 'Yuval Noah Harari', 2011, 'Historia de la humanidad', 'Editorial Debate', 'Revelador'),
(null, 1, 'Los pilares de la tierra', 'Ken Follett', 1989, 'La construcción de una catedral en la Edad Media', 'Editorial Planeta', 'Epico'),
(null, 1, 'La chica del tren', 'Paula Hawkins', 2015, 'Un thriller psicológico', 'Editorial Planeta', 'Adictivo'),
(null, 1, 'El silencio de los corderos', 'Thomas Harris', 1988, 'Un asesino en serie y una agente del FBI', 'Editorial Planeta', 'Impactante'),
(null, 1, 'La sombra del viento', 'Carlos Ruiz Zafón', 2001, 'Un misterio literario en Barcelona', 'Editorial Planeta', 'Absorbente'),
(null, 2, 'La niña que soñaba con una cerilla y un bidón de gasolina', 'Stieg Larsson', 2006, 'Un thriller oscuro', 'Editorial Destino', 'Intenso'),
(null, 2, 'El alquimista', 'Paulo Coelho', 1988, 'Un viaje espiritual', 'Editorial Planeta', 'Inspirador'),
(null, 2, 'Los hombres que no amaban a las mujeres', 'Stieg Larsson', 2005, 'Un misterio en Suecia', 'Editorial Destino', 'Adictivo'),
(null, 2, 'Un mundo feliz', 'Aldous Huxley', 1932, 'Una distopía sobre la sociedad futura', 'Editorial DeBolsillo', 'Provocador'),
(null, 2, 'El retrato de Dorian Gray', 'Oscar Wilde', 1890, 'La historia de un hombre y su retrato', 'Editorial Alianza', 'Fascinante'),
(null, 2, 'Revolución en la granja', 'George Orwell', 1945, 'Una sátira sobre el totalitarismo', 'Editorial Debolsillo', 'Provocador'),
(null, 2, 'Mujer en punto cero', 'Nawal El Saadawi', 1975, 'La historia de una prisionera', 'Editorial Feminismos', 'Impactante'),
(null, 2, 'El diario de Ana Frank', 'Ana Frank', 1947, 'Las memorias de una niña en la Segunda Guerra Mundial', 'Editorial Debate', 'Emotivo'),
(null, 2, 'La tregua', 'Mario Benedetti', 1960, 'La historia de un hombre que encuentra el amor', 'Editorial Alfaguara', 'Hermosa'),
(null, 2, 'En el camino', 'Jack Kerouac', 1957, 'Una novela sobre la búsqueda de la libertad', 'Editorial Cátedra', 'Revolucionario'),
(null, 2, 'El hombre en busca de sentido', 'Viktor Frankl', 1946, 'Reflexiones sobre la vida en un campo de concentración', 'Editorial Herder', 'Profundo'),
(null, 3, 'Cien años de soledad', 'Gabriel García Márquez', 1967, 'La historia de la familia Buendía', 'Editorial Sudamericana', 'Un clásico'),
(null, 3, 'El túnel', 'Ernesto Sabato', 1948, 'Una historia de amor obsesivo', 'Editorial Seix Barral', 'Profundo'),
(null, 3, 'El gran Gatsby', 'F. Scott Fitzgerald', 1925, 'Una crítica de la sociedad de los años 20', 'Editorial Anagrama', 'Trágico'),
(null, 3, 'Rayuela', 'Julio Cortázar', 1963, 'Una novela que se puede leer de diferentes maneras', 'Editorial Sudamericana', 'Experimental'),
(null, 3, 'El marqués de Sade', 'Alfred de Musset', 1850, 'La vida de un polémico escritor', 'Editorial Alianza', 'Controversial'),
(null, 3, 'Las uvas de la ira', 'John Steinbeck', 1939, 'La lucha de una familia durante la Gran Depresión', 'Editorial Debolsillo', 'Emotivo'),
(null, 3, 'Fuego y sangre', 'George R.R. Martin', 2018, 'Historia de la Casa Targaryen', 'Editorial Gigamesh', 'Épico'),
(null, 3, 'Cumbres borrascosas', 'Emily Brontë', 1847, 'Una historia de amor y venganza', 'Editorial Alianza', 'Intenso'),
(null, 3, 'El conde de Montecristo', 'Alexandre Dumas', 1844, 'Una historia de venganza', 'Editorial Planeta', 'Épico'),
(null, 3, 'En busca del tiempo perdido', 'Marcel Proust', 1913, 'Una exploración de la memoria', 'Editorial Gallimard', 'Profundo'),
(null, 3, 'Bajo el volcán', 'Malcolm Lowry', 1947, 'La historia de un cónsul británico', 'Editorial Anagrama', 'Trágico'),
(null, 3, 'El lobo estepario', 'Hermann Hesse', 1927, 'La lucha entre el hombre y su naturaleza', 'Editorial Tusquets', 'Filosófico'),
(null, 1, 'La lluvia de fuego', 'Jorge Luis Borges', 1974, 'Un relato sobre el tiempo y el destino', 'Editorial Emecé', 'Misterioso'),
(null, 1, 'El último encuentro', 'Sándor Márai', 1942, 'Un diálogo entre amigos que se reencuentran', 'Editorial Salamandra', 'Profundo'),
(null, 1, 'En el camino de Swann', 'Marcel Proust', 1913, 'Exploración de la memoria y el tiempo', 'Editorial Gallimard', 'Introspectivo'),
(null, 1, 'Cuentos de la selva', 'Horacio Quiroga', 1918, 'Relatos sobre la vida en la selva', 'Editorial Alianza', 'Aventurero'),
(null, 1, 'El corazón de las tinieblas', 'Joseph Conrad', 1899, 'Una crítica del colonialismo', 'Editorial Ediciones Akal', 'Perturbador'),
(null, 1, 'El extranjero', 'Albert Camus', 1942, 'Reflexiones sobre la vida y la muerte', 'Editorial Alianza', 'Existencialista'),
(null, 1, 'La mujer en el umbral', 'María Dueñas', 2016, 'Un relato de amor y superación', 'Editorial Planeta', 'Inspirador'),
(null, 1, 'Mujer en guerra', 'Sofía Casanova', 1918, 'La vida de mujeres en tiempos de guerra', 'Editorial Planeta', 'Impactante'),
(null, 2, 'El príncipe', 'Nicolás Maquiavelo', 1532, 'Un tratado sobre el poder político', 'Editorial Espasa', 'Controversial'),
(null, 2, 'El viejo y el mar', 'Ernest Hemingway', 1952, 'La lucha de un viejo pescador', 'Editorial Debolsillo', 'Emotivo'),
(null, 2, 'La casa de los espíritus', 'Isabel Allende', 1982, 'La historia de una familia a lo largo de generaciones', 'Editorial Plaza & Janés', 'Mágico'),
(null, 2, 'Ficciones', 'Jorge Luis Borges', 1944, 'Una colección de relatos fantásticos', 'Editorial Emecé', 'Intrigante'),
(null, 2, 'Crónica de una muerte anunciada', 'Gabriel García Márquez', 1981, 'Un asesinato que todos conocen', 'Editorial Random House', 'Impactante'),
(null, 2, 'Los miserables', 'Victor Hugo', 1862, 'La lucha por la redención', 'Editorial Alianza', 'Épico'),
(null, 2, 'La chica del tren', 'Paula Hawkins', 2015, 'Un thriller psicológico', 'Editorial Planeta', 'Adictivo'),
(null, 2, 'La metafísica de los tubos', 'Amélie Nothomb', 2000, 'Una novela sobre la vida y la muerte', 'Editorial Anagrama', 'Filosófico'),
(null, 2, 'La suerte de los idiotas', 'Santiago Roncagliolo', 2011, 'Una novela negra', 'Editorial Alfaguara', 'Divertido'),
(null, 2, 'Ensayo sobre la ceguera', 'José Saramago', 1995, 'Una alegoría sobre la condición humana', 'Editorial Alfaguara', 'Impactante'),
(null, 2, 'La vida es sueño', 'Pedro Calderón de la Barca', 1635, 'Una reflexión sobre la realidad y los sueños', 'Editorial Espasa', 'Clásico'),
(null, 3, 'El nombre de la rosa', 'Umberto Eco', 1980, 'Un misterio en una abadía medieval', 'Editorial Mondadori', 'Intrigante'),
(null, 3, 'El oro del Rin', 'Richard Wagner', 1869, 'Una ópera en forma de novela', 'Editorial Alianza', 'Épico'),
(null, 3, 'Cien años de soledad', 'Gabriel García Márquez', 1967, 'La historia de la familia Buendía', 'Editorial Sudamericana', 'Un clásico'),
(null, 3, 'El cuento de la criada', 'Margaret Atwood', 1985, 'Una distopía sobre el control de las mujeres', 'Editorial Salamandra', 'Perturbador'),
(null, 3, 'Mujercitas', 'Louisa May Alcott', 1868, 'La vida de cuatro hermanas en América', 'Editorial Anagrama', 'Tierno'),
(null, 3, 'El hombre que ríe', 'Victor Hugo', 1869, 'La historia de un hombre desfigurado', 'Editorial Alianza', 'Trágico'),
(null, 3, 'La tierra de la gran promesa', 'Jerzy Kosinski', 1971, 'Un viaje de autodescubrimiento', 'Editorial Anagrama', 'Filosófico'),
(null, 3, 'El retrato de Dorian Gray', 'Oscar Wilde', 1890, 'La historia de un hombre y su retrato', 'Editorial Alianza', 'Fascinante'),
(null, 3, 'Siddhartha', 'Hermann Hesse', 1922, 'La búsqueda espiritual de un hombre', 'Editorial Tusquets', 'Profundo'),
(null, 3, 'La isla del tesoro', 'Robert Louis Stevenson', 1883, 'Una aventura de piratas', 'Editorial Anagrama', 'Aventurero'),
(null, 3, 'Don Quijote de la Mancha', 'Miguel de Cervantes', 1605, 'La historia de un caballero loco', 'Editorial Alianza', 'Clásico'),
(null, 3, 'Cumbres borrascosas', 'Emily Brontë', 1847, 'Una historia de amor y venganza', 'Editorial Alianza', 'Intenso'),
(null, 3, 'Orgullo y prejuicio', 'Jane Austen', 1813, 'La historia de un amor y sus malentendidos', 'Editorial Alianza', 'Romántico');